-- 날짜 시간으로 구성된 DATE_OF_BIRTH의 출력 형식을 DATE_FORMAT으로 재정의하기!
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') AS DATE_OF_BIRTH FROM MEMBER_PROFILE 
WHERE TLNO IS NOT NULL AND GENDER = 'W' AND DATE_OF_BIRTH LIKE '%-03-%' 
ORDER BY MEMBER_ID;


-- MONTH(DATE_OF_BIRTH)=3로 생일이 3월인 사람을 판별할 수 있다.
