SELECT FLAVOR
FROM FIRST_HALF NATURAL JOIN ICECREAM_INFO
WHERE TOTAL_ORDER > 3000 AND INGREDIENT_TYPE = 'fruit_based';


-- FLAVOR은 공통 칼럼이므로 테이블 명 작성이 필수이다!
-- 그냥 JOIN을 사용했을 경우에 조인하는 테이블의 on 절의 조건이 일치하는 결과만 출력한다!
SELECT A.FLAVOR
FROM FIRST_HALF A JOIN ICECREAM_INFO B ON A.FLAVOR = B.FLAVOR
WHERE (A.TOTAL_ORDER > 3000) AND (B.INGREDIENT_TYPE = 'fruit_based')
ORDER BY A.TOTAL_ORDER DESC;
