-- HAVING 절에서 다 해결해줘도 됨
SELECT NAME, COUNT(NAME) AS COUNT
FROM ANIMAL_INS
GROUP BY NAME
HAVING NAME IS NOT NULL AND COUNT(NAME)>=2
ORDER BY NAME;

-- HAVING 절 말고 WHERE 절에서 NULL 이 아닌 값을 빼줘도 된다
SELECT NAME, COUNT(NAME) AS 'COUNT'
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
GROUP BY NAME
HAVING COUNT(NAME) >= 2
ORDER BY NAME;
