SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE),2) SCORE
FROM REST_INFO I JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
GROUP BY I.REST_ID
HAVING I.ADDRESS LIKE '서울%'
ORDER BY AVG(R.REVIEW_SCORE) DESC, FAVORITES DESC;


-- rest_id로 그룹화한 뒤 having을 통해 그룹화한 곳의 원하는 조건인 서울을 가져온다!
